"use strict";
exports.__esModule = true;
var dotenv_1 = require("dotenv");
(0, dotenv_1.config)();
var express = require("express");
var cors = require("cors");
var bodyParser = require("body-parser");
var db_1 = require("./db/db");
var app = express();
var PORT = process.env.PORT || 8000;
var apiRoutes = require("./routes/reportRouter");
(0, db_1.connectDB)();
app.use(cors());
app.use(express.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
app.use("/reports", apiRoutes);
app.listen(PORT, function () { return console.log("Server running on port ".concat(PORT)); });
